#include <SoftwareSerial.h>
#include <SerialCommand.h>


int transmitPin = 2; 
SerialCommand sCmd;     // The demo SerialCommand object

void setup()
{
	pinMode(transmitPin,OUTPUT);
	digitalWrite(transmitPin,LOW);
	Serial.begin(9600);

	// Setup callbacks for SerialCommand commands
	sCmd.addCommand("up",	Up);          // Turns LED on
	sCmd.addCommand("down",	Down);         // Turns LED off
	sCmd.addCommand("stop", Stop);        // Echos the string argument back
	sCmd.setDefaultHandler(unrecognized);      // Handler for command that isn't matched  (says "What?")
	Serial.println("Ready:");
}

void loop() {
	sCmd.readSerial();
}

void Down() {
	//screen down
	Serial.print("transmitting ScreenDown\n");
    screenDown();
    screenDown();
    delay(100);
    screenDown();
    screenDown();
    delay(100);
    screenDown();
    screenDown();
    delay(4600);
    Serial.print("transmitted ScreenDown\n");

}

void Stop() {
    //screen stop
    Serial.print("transmitting ScreenStop\n");
    screenStop();
    screenStop();
    delay(10);
    screenStop();
    screenStop();
    delay(4600);
    Serial.print("transmitted ScreenStop\n");
}
   
void Up() {
	//screen up
	Serial.print("transmitting ScreenUp\n");
    screenUp();
    screenUp();
    delay(10);
    screenUp();
    screenUp();
    delay(4600);
    Serial.print("transmitted ScreenUp\n");
}

void customDelay(unsigned long time) 
{
    unsigned long end_time = micros() + time;
    while(micros() < end_time);
}

//1000=1ms
void setStateWithDelay(int pin, int state,int delayTime)
{
  if(state==1)
    digitalWrite(pin,HIGH);
  else
    digitalWrite(pin,LOW);
    
  customDelay(delayTime);
}

// This gets set as the default handler, and gets called when no other command matches.
void unrecognized(const char *command) {
	Serial.println("unknown command:");
}
void screenUp()
{
	setStateWithDelay(transmitPin,0,44500);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,4600);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,4600);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,4600);
	digitalWrite(transmitPin,LOW);

}

void screenDown()
{
	setStateWithDelay(transmitPin,0,000);
	setStateWithDelay(transmitPin,1,300);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,4600);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,4700);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,4600);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,4600);
	digitalWrite(transmitPin,LOW);
}

void screenStop()
{
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,4600);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,4600);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,200);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,100);
	setStateWithDelay(transmitPin,0,500);
	setStateWithDelay(transmitPin,1,400);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,500);
	setStateWithDelay(transmitPin,0,100);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,400);
	setStateWithDelay(transmitPin,1,200);
	setStateWithDelay(transmitPin,0,4600);
	digitalWrite(transmitPin,LOW);
}
